name = "GitTest"
uuid = "cdf3f76e-b0d4-4e66-866f-dc01d0cc4c90"
authors = ["abmnjm"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
